name: Docker Image CI

on:
  push:
    branches:
    - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.BYOAIA_ACR_USERNAME }}
        # Container registry password
        password: ${{ secrets.BYOAIA_ACR_PASSWORD }}
        # Container registry server url
        login-server: byoaiacontainer.azurecr.io
        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run:     
        cd "App";   
        docker build . --file WebApp.Dockerfile --tag byoaiacontainer.azurecr.io/byoaia-app:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker tag byoaiacontainer.azurecr.io/byoaia-app:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER byoaiacontainer.azurecr.io/byoaia-app:latest;
        docker push byoaiacontainer.azurecr.io/byoaia-app:$(date +'%Y-%m-%d')_$GITHUB_RUN_NUMBER;
        docker push byoaiacontainer.azurecr.io/byoaia-app:latest;
      
